#!/usr/bin/php
<?php
$pid = pcntl_fork();
if ($pid == -1) {
     die('could not fork');
} else if ($pid) {
     // we are the parent
     pcntl_wait($status); //Protect against Zombie children
} else {
     // we are the child
//chdir('/srv/http');
chdir('../');
include("includes/config.inc");
include("includes/string/simple.inc");
include("includes/link.inc");
include("includes/forms/submit.inc");
include("includes/forms/build.inc");
include("includes/modules/hook.inc");
include("includes/modules/load.inc");
include("includes/menu/build.inc");
include("includes/theme/build.inc");

$project['debug'] = 2;

play_command_load_commands();
while(true) {
	sleep(2);
	play_command_execute('doorlock_cron');
}
}

