

                        </td>
                </tr>
                </table>
        </td>
</tr>
<style type="text/css">
<!--
.footer_text {font-family:Verdana,Arial,Helvetica,sans-serif;font-size:10px;color:#666666;line-height:15px;}
.style2 {font-family: Verdana,Arial,Helvetica,sans-serif; font-size: 14px; color: #2D0000; line-height: 15px; }
-->
</style>

<tr  bgcolor="#E0E0E0">
        <td align=center>
               <font face=verdana size=-2></font>
        </td>
</tr>
</table>
<span class="style2">&copy;2013-2014 Customer Informer Group, All rights reserved.</span>
</body>
</html>
