<html>
<head>
<title><?php echo $project['title']; ?></title>
<link class="common" href="themes/default/default.css" rel="stylesheet" type="text/css" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"></head>
<body >
<table width=1000 border=0 cellpadding=0 cellspacing=1>
<tr class='common_top'>
  <td><br>
    <h3 align="center" class="style1"><center>
    <span class="style2"><img src="<?php echo $project['logo']; ?>" width="116" height="89"><span class="style5"><?php echo $project['heading']; ?></span> </span></center></h3></td>
</tr>
<tr>
        <td align=center>
                <table width=100% cellpadding=0 cellspacing=1 border=0>
                <tr align=center>                </tr>
                </table>        </td>
</tr>
<tr>
        <td>
                <table width=100% height=400 border=0 cellpadding=10 cellspacing=0>
                <tr valign=top>
                        <td class='common_left' width=135>                        </td>
<td class='common_center'>


